apiVersion: apps/v1
kind: Deployment
metadata:
  name: elfo-one
  namespace: santa
spec:
  selector:
    matchLabels:
      app: elfo-one
  template:
    metadata:
      labels:
        app: elfo-one
    spec:
      containers:
      - name: elfo-one
        image: santaclause.azurecr.io/elfo-one:0.0.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: elfo-one-service
  namespace: santa
spec:
  selector:
    app: elfo-one
  ports:
  - port: 80
    targetPort: 80

