apiVersion: apps/v1
kind: Deployment
metadata:
  name: elfo-two
  namespace: santa
spec:
  selector:
    matchLabels:
      app: elfo-two
  template:
    metadata:
      labels:
        app: elfo-two
    spec:
      containers:
      - name: elfo-two
        image: santaclause.azurecr.io/elfo-two:0.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: elfo-two-service
  namespace: santa
spec:
  selector:
    app: elfo-two
  ports:
  - port: 80
    targetPort: 80

