apiVersion: v1
kind: ConfigMap
metadata:
  name: yarp-config
  namespace: santa
data:
  yarp.json: |
    {
      "Yarp": {
        "ControllerClass": "microsoft.com/ingress-yarp",
        "ServerCertificates": false,
        "DefaultSslCertificate": "yarp/yarp-ingress-tls"
      },
      "ReverseProxy": {
        "Routes": {
          "aggregator-route": {
            "ClusterId": "aggregator",
            "Match": {
              "Path": "/a/{**catch-all}"
            },
            "Transforms": [
              { "PathRemovePrefix": "/a" }
            ]
          },
          "serviceone-route": {
            "ClusterId": "elfo-one",
            "Match": {
              "Path": "/o/{**catch-all}"
            },
            "Transforms": [
              { "PathRemovePrefix": "/o" }
            ]
          },
          "servicetwo-route": {
            "ClusterId": "elfo-two",
            "Match": {
              "Path": "/t/{**catch-all}"
            },
            "Transforms": [
              { "PathRemovePrefix": "/t" }
            ]
          }
        },
        "Clusters": {
          "aggregator": {
            "Destinations": {
              "default": {
                "Address": "http://aggregator-service.santa.svc.cluster.local/"
              }
            }
          },
          "elfo-one": {
            "Destinations": {
              "default": {
                "Address": "http://elfo-one-service.santa.svc.cluster.local/"
              }
            }
          },
          "elfo-two": {
            "Destinations": {
              "default": {
                "Address": "http://elfo-two-service.santa.svc.cluster.local/"
              }
            }
          }
        }
      }
    }
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: yarp-serviceaccount
  namespace: santa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: yarp-ingress-clusterrole
  namespace: santa
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - nodes
  - pods
  - secrets
  - namespaces
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  - extensions
  - networking.internal.knative.dev
  resources:
  - ingresses
  - ingressclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - networking.k8s.io
  - extensions
  - networking.internal.knative.dev
  resources:
  - ingresses/status
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: yarp-ingress-clusterrole-nisa-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: yarp-ingress-clusterrole
subjects:
- kind: ServiceAccount
  name: yarp-serviceaccount
  namespace: santa
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: yarp
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: microsoft.com/ingress-yarp